O objetivo deste exercício é utilizar a base de dados do crédito e aplicar a técnica de seleção de atributos utilizando variância.

- Carregue o arquivo credit_data.csv

- Calcule a variância para os atributos income, age e loan e aplique o método de seleção Low Variance

- Faça um teste do accuracy utilizando o algoritmo Naïve Bayes, sem seleção de atributos e com seleção de atributos


In [72]:
import pandas as pd 
from sklearn.feature_selection import VarianceThreshold
from sklearn.preprocessing import MinMaxScaler
import numpy as np 

In [41]:
df = pd.read_csv('../data/credit_data.csv')
df.dropna(inplace=True)
df.head()

i#clientid        income        age         loan  c#default
0           1  66155.925095  59.017015  8106.532131          0
1           2  34415.153966  48.117153  6564.745018          0
2           3  57317.170063  63.108049  8020.953296          0
3           4  42709.534201  45.751972  6103.642260          0
4           5  66952.688845  18.584336  8770.099235          1

In [42]:
df.describe()

i#clientid        income          age          loan    c#default
count  1997.000000   1997.000000  1997.000000   1997.000000  1997.000000
mean   1001.956935  45333.864334    40.807559   4445.487716     0.141713
std     576.702206  14325.131177    13.624469   3046.792457     0.348842
min       1.000000  20014.489470   -52.423280      1.377630     0.000000
25%     503.000000  32804.904487    28.990415   1936.813257     0.000000
50%    1002.000000  45788.747100    41.317159   3977.287432     0.000000
75%    1501.000000  57787.565659    52.587040   6440.861434     0.000000
max    2000.000000  69995.685578    63.971796  13766.051239     1.000000

In [43]:
df.iloc[:, 1:4].values

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [44]:
X = df.iloc[:, 1:4].values
y = df.iloc[:, 4:].values

In [67]:
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

In [73]:
np.var(X[0]), np.var(X[1]), np.var(X[2])

(0.027646353650092215, 0.057415153407223446, 0.02838948027619903)

In [76]:
selecao = VarianceThreshold(0.027)
X_novo = selecao.fit_transform(X)
X_novo

array([[0.9231759 , 0.58883739],
       [0.28812165, 0.47682695],
       [0.74633429, 0.58262011],
       ...,
       [0.48612202, 0.40112895],
       [0.47500998, 0.1177903 ],
       [0.98881367, 0.53597028]])

In [77]:
X.shape, X_novo.shape

((1997, 3), (1997, 2))

In [78]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

In [79]:
naive_bayes = GaussianNB()
resultados_naive_bayes = cross_val_score(naive_bayes, X, y, cv=30)
resultados_naive_bayes

array([0.88059701, 0.95522388, 0.89552239, 0.97014925, 0.8358209 ,
       0.94029851, 0.97014925, 0.91044776, 0.98507463, 0.91044776,
       0.89552239, 0.95522388, 0.91044776, 0.89552239, 0.95522388,
       0.97014925, 0.94029851, 0.89393939, 0.93939394, 0.92424242,
       0.95454545, 0.93939394, 0.90909091, 0.89393939, 0.89393939,
       0.92424242, 0.90909091, 0.95454545, 0.93939394, 0.89393939])

In [80]:
naive_bayes = GaussianNB()
resultados_naive_bayes = cross_val_score(naive_bayes, X_novo, y, cv=30)
resultados_naive_bayes

array([0.85074627, 0.86567164, 0.79104478, 0.85074627, 0.85074627,
       0.85074627, 0.85074627, 0.82089552, 0.85074627, 0.8358209 ,
       0.85074627, 0.82089552, 0.79104478, 0.8358209 , 0.86567164,
       0.8358209 , 0.86567164, 0.81818182, 0.86363636, 0.84848485,
       0.84848485, 0.89393939, 0.87878788, 0.86363636, 0.86363636,
       0.81818182, 0.87878788, 0.8030303 , 0.86363636, 0.84848485])

como pode ser visto a aplicação desse metodo nessa base de dados não ira melhorar a acuracia